# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --install-hooks
#

ci:
  # pre-commit.ci will open PRs updating our hooks once a month
  autoupdate_schedule: monthly

repos:
  # autoformat and lint Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        types_or:
          - python
          - jupyter
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
        types_or:
          - python
          - jupyter

  # Autoformat: markdown, yaml, javascript (see the file .prettierignore)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: .*/templates/.*

  # autoformat HTML templates
  - repo: https://github.com/djlint/djLint
    rev: v1.35.2
    hooks:
      - id: djlint-reformat-jinja
        files: ".*templates/.*.html"
        types_or: ["html"]
        exclude: redoc.html
      - id: djlint-jinja
        files: ".*templates/.*.html"
        types_or: ["html"]

  # Autoformat and linting, misc. details
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: share/jupyterhub/static/js/admin-react.js
      - id: requirements-txt-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
