language: python
sudo: false
cache:
  - pip
python:
  - 3.6
  - 3.5
  - nightly
env:
  global:
    - ASYNC_TEST_TIMEOUT=15
    - MYSQL_HOST=127.0.0.1
    - MYSQL_TCP_PORT=13306
services:
  - postgres
  - docker

# installing dependencies
before_install:
  - set -e
  - nvm install 6; nvm use 6
  - npm install
  - npm install -g configurable-http-proxy
  - |
    # setup database
    if [[ $JUPYTERHUB_TEST_DB_URL == mysql* ]]; then
      unset MYSQL_UNIX_PORT
      DB=mysql bash ci/docker-db.sh
      DB=mysql bash ci/init-db.sh
      pip install 'mysql-connector-python'
    elif [[ $JUPYTERHUB_TEST_DB_URL == postgresql* ]]; then
      psql -c "CREATE USER $PGUSER WITH PASSWORD '$PGPASSWORD';" -U postgres
      DB=postgres bash ci/init-db.sh
      pip install psycopg2-binary
    fi
install:
  - pip install --upgrade pip
  - pip install --upgrade --pre -r dev-requirements.txt .
  - pip freeze

# running tests
script:
  - |
    # run tests
    if [[ -z "$TEST" ]]; then
      pytest -v --maxfail=2 --cov=jupyterhub jupyterhub/tests
    fi
  - |
    # run autoformat
    if [[ "$TEST" == "lint" ]]; then
      pre-commit run --all-files
    fi
  - |
    # build docs
    if [[ "$TEST" == "docs" ]]; then
      pushd docs
      pip install --upgrade -r requirements.txt
      pip install --upgrade alabaster_jupyterhub
      make html
      popd
    fi
after_success:
  - codecov
after_failure:
  - |
    # point to auto-lint-fix
    if [[ "$TEST" == "lint" ]]; then
      echo "You can install pre-commit hooks to automatically run formatting"
      echo "on each commit with:"
      echo "    pre-commit install"
      echo "or you can run by hand on staged files with"
      echo "    pre-commit run"
      echo "or after-the-fact on already committed files with"
      echo "    pre-commit run --all-files"
    fi

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TEST=lint
    - python: 3.6
      env: TEST=docs
    - python: 3.6
      env: JUPYTERHUB_TEST_SUBDOMAIN_HOST=http://localhost.jovyan.org:8000
    - python: 3.6
      env:
        - JUPYTERHUB_TEST_DB_URL=mysql+mysqlconnector://root@127.0.0.1:$MYSQL_TCP_PORT/jupyterhub
    - python: 3.6
      env:
        - PGUSER=jupyterhub
        - PGPASSWORD=hub[test/:?
        # password in url is url-encoded (urllib.parse.quote($PGPASSWORD, safe=''))
        - JUPYTERHUB_TEST_DB_URL=postgresql://jupyterhub:hub%5Btest%2F%3A%3F@127.0.0.1/jupyterhub
    - python: 3.7
      dist: xenial
  allow_failures:
    - python: nightly
