language: python
sudo: false
cache:
  - pip
python:
  - 3.6
  - 3.5
  - nightly
env:
  global:
    - ASYNC_TEST_TIMEOUT=15
services:
  - postgres
  - docker

# installing dependencies
before_install:
  - nvm install 6; nvm use 6
  - npm install
  - npm install -g configurable-http-proxy
  - |
    # setup database
    if [[ $JUPYTERHUB_TEST_DB_URL == mysql* ]]; then
      unset MYSQL_UNIX_PORT
      DB=mysql bash ci/docker-db.sh
      DB=mysql bash ci/init-db.sh
      pip install 'mysql-connector<2.2'
    elif [[ $JUPYTERHUB_TEST_DB_URL == postgresql* ]]; then
      DB=postgres bash ci/init-db.sh
      pip install psycopg2
    fi
install:
  - pip install --upgrade pip
  - pip install --pre -r dev-requirements.txt .
  - pip freeze

# running tests
script:
  - |
    # create old database for upgrading
    set -e
    if [[ ! -z "$JUPYTERHUB_TEST_DB_URL" ]]; then
      # if testing upgrade-db, run `jupyterhub token` with 0.7
      # to initialize an old db. Used in upgrade-tests
      export JUPYTERHUB_TEST_UPGRADE_DB_URL=${JUPYTERHUB_TEST_DB_URL}_upgrade
      # use virtualenv instead of venv because venv doesn't work here
      python -m pip install virtualenv
      python -m virtualenv old-hub-env
      ./old-hub-env/bin/python -m pip install jupyterhub==0.7.2 psycopg2 'mysql-connector<2.2'
      ./old-hub-env/bin/jupyterhub token kaylee \
        --JupyterHub.db_url=$JUPYTERHUB_TEST_UPGRADE_DB_URL \
        --Authenticator.whitelist="{'kaylee'}" \
        --JupyterHub.authenticator_class=jupyterhub.auth.Authenticator
    fi
  - pytest -v --maxfail=2 --cov=jupyterhub jupyterhub/tests
  - |
    # build docs
    pushd docs
    pip install -r requirements.txt
    make html
    popd
after_success:
  - codecov

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: JUPYTERHUB_TEST_SUBDOMAIN_HOST=http://localhost.jovyan.org:8000
    - python: 3.6
      env:
        - MYSQL_HOST=127.0.0.1
        - MYSQL_TCP_PORT=13306
        - JUPYTERHUB_TEST_DB_URL=mysql+mysqlconnector://root@127.0.0.1:$MYSQL_TCP_PORT/jupyterhub
    - python: 3.6
      env:
        - JUPYTERHUB_TEST_DB_URL=postgresql://postgres@127.0.0.1/jupyterhub
  allow_failures:
    - python: nightly
