# http://travis-ci.org/#!/jupyter/jupyterhub
language: python
python:
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - nightly

# installing dependencies
before_install:
    - npm install
    - npm install -g configurable-http-proxy
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install --pre -f travis-wheels/wheelhouse -r dev-requirements.txt .

# running tests
script:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' || $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then pytest --cov=jupyterhub jupyterhub/tests; fi # for Python 3.6 and above
    - if [[ $TRAVIS_PYTHON_VERSION == '3.5' || $TRAVIS_PYTHON_VERSION == '3.4' || $TRAVIS_PYTHON_VERSION == '3.3' ]]; then py.test --cov=jupyterhub jupyterhub/tests; fi # for < 3.5
after_success:
    - codecov

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: JUPYTERHUB_TEST_SUBDOMAIN_HOST=http://127.0.0.1.xip.io:8000
