# http://travis-ci.org/#!/jupyter/jupyterhub
language: python
python:
    - nightly
    - 3.6
    - 3.5
    - 3.4
    - 3.3


# installing dependencies
before_install:
    - npm install
    - npm install -g configurable-http-proxy
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install --pre -f travis-wheels/wheelhouse -r dev-requirements.txt .

# running tests
script:
    - pytest --maxfail=2 --cov=jupyterhub jupyterhub/tests
after_success:
    - codecov

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: JUPYTERHUB_TEST_SUBDOMAIN_HOST=http://localhost.jovyan.org:8000
