contact_links:
  - name: "\U0001F914 All other questions, including if you're not sure what to do."
    url: https://discourse.jupyter.org
    about: Search on Discourse for similar questions or ask for help there.
