# ReadTheDocs uses the `environment.yaml` so make sure to update that as well
# if you change the dependencies of JupyterHub in the various `requirements.txt`
name: jhub_docs
channels:
  - conda-forge
dependencies:
- pip
- nodejs
- python=3.6
- alembic
- jinja2
- pamela
- requests
- sqlalchemy>=1
- tornado>=5.0
- traitlets>=4.1
- sphinx>=1.7
- pip:
  - entrypoints
  - oauthlib>=2.0
  - recommonmark==0.5.0
  - async_generator
  - prometheus_client
  - attrs>=17.4.0
  - sphinx-copybutton
  - alabaster_jupyterhub
  - autodoc-traits
